### PR TITLE
Redesign posts and pages

### LINKED ISSUE #123: frontend Edit post bug
step to reproduce:
1. create a test1
2. create another test2

actual: 
test1 is not editable, while test2 is
image

expect: both post to be able to edit, delete

### LINKED ISSUE #124: Frontend Delete post bug
deleting a post causing the post  to think it is my post when it is not

Step to reproduce:
1. Delete post test2 (made by me: hiufungk)
image
image

### PR DESCRIPTION
**Pull request by shchau**
resolves #123 
resolves #124 

Added headers to pages. 
displayName for Author, Stream for Stream, Friends for Friends, Public for PublicStream.

Made it so auto-scroll in Author only happens upon clicking the Edit button.

Fixed visibility settings to handle private appropriately. 
Fixed stream feed bug where edit/delete buttons were appearing on posts based on ID for some reason.
Changed alerts to toasts. 

Screenshot_2019-03-19_23-48-14
Screenshot_2019-03-19_23-48-33
Screenshot_2019-03-19_23-48-22
Screenshot_2019-03-19_23-48-28
Screenshot_2019-03-19_23-48-41
Screenshot_2019-03-19_23-48-50

### CODE REVIEW

File: frontend/src/components/CreatePostModal.jsx [hunk 1]
```diff
@@ -168,7 +170,7 @@ class CreatePostModal extends Component {
 
 	handleSubmit(event) {
 		const requireAuth = true;
-		const requestBody = {
+		var requestBody = {
```
Comment (hiufungk) [inline frontend/src/components/CreatePostModal.jsx:174]: why change from const to var

File: frontend/src/components/CreatePostModal.jsx [hunk 2]
```diff
@@ -284,81 +321,81 @@ class CreatePostModal extends Component {
...
+			<Modal 
+				trigger={this.props.modalTrigger}
+				open={this.props.showModal}
+				onClose={this.closeModal}
+				className={"createPostModal"}
+			>
+				{$modalHeader}
+				<Modal.Content className="postModalContent">
+				
+				{this.state.createPostPageOne ?
```
Comment (hiufungk) [inline frontend/src/components/CreatePostModal.jsx]: no giant ternary expression please :'(

File: frontend/src/components/StreamFeed.jsx [hunk 3]
```diff
@@ -25,11 +27,10 @@ class StreamFeed extends Component {
  		this.setState({ showModal: false});
 	}
 
-	createPostFromJson(key, payload){
+	createPostFromJson(payload){
 		return(
 			<StreamPost 
-			key={key}
-			index={key}
+			key={payload.id}
```
Comment (hiufungk) [inline frontend/src/components/StreamFeed.jsx:33]: some prop-types missing in stream post

**Review by hiufungk — CHANGES_REQUESTED** [review]

**Comment by hiufungk** [comment]
personally not a big fan of the text on top left corner. Maybe style the nav bar to indicate which page you are on instead?

File: frontend/src/components/CreatePostModal.jsx (hunk 1 above)
Comment (shchau) [reply frontend/src/components/CreatePostModal.jsx:174]: Because then I can change visibleTo to be blank if visibility is not set to private. 
Lets user preserve previous visibleTo settings too.

File: frontend/src/components/CreatePostModal.jsx (hunk 2 above)
Comment (shchau) [reply frontend/src/components/CreatePostModal.jsx]: oml it just gets moved up but okay  
:'(

**Comment by shchau** [comment]
> personally not a big fan of the text on top left corner. Maybe style the nav bar to indicate which page you are on instead?

Do you wanna restyle the Sidebar using your other version? :U 
I was also thinking of hiding the Sidebar in a button that has the text of the current thing you're on, but that'll take more work than we can afford atm probably.

**Review by hiufungk — APPROVED** [review]

**Review by forgeno — APPROVED** [review]
