### PR TITLE
Login bugs

### LINKED ISSUE #130: Frontend Login bug
Steps to reproduce:
1. register user1
2. click confirm and get 200 OK, redirect to login component
3. register user2 confirm and get 200OK -> does not redirect to login component anymore

### PR DESCRIPTION
**Pull request by shchau**
resolves #130 
resolves #180 

Login boxes will no longer always be red.
Login successes will not display the login failure message.

Changed register to not use redux at all and just rely on a normal fetch request.
Register shoould always redirect on register successes now.

### CODE REVIEW

File: frontend/src/components/LoginFormComponent.jsx [hunk 1]
```diff
@@ -28,12 +29,16 @@ class LoginFormComponent extends Component {
             urlPath = "/api/auth/login/",
             requestBody = {username: this.state.username,
                         password: this.state.password};
+                        
         this.props.sendLogin(urlPath, requireAuth, requestBody)
         let loginAttemptNum = this.state.loginAttempt
```
Comment (forgeno) [inline frontend/src/components/LoginFormComponent.jsx]: change to const if  you aren't changing it

Comment (shchau) [reply frontend/src/components/LoginFormComponent.jsx]: Okie I got rid of it and just used this.state.loginAttempt instead

**Review by forgeno — APPROVED** [review]

**Review by derrick-w — APPROVED** [review]
idk looks ok
